print('hello')
print('hello world')
print('again')
print('group learning')
print('where are you')
print('how are you')
print('hello world')
print('again')
print('group learning')
print('where are you')
print('try')
print('how are you')
